INSERT INTO CATEGORIAS (nome) VALUES ('Praia');
INSERT INTO CATEGORIAS (nome) VALUES ('Montanha');
INSERT INTO CATEGORIAS (nome) VALUES ('Mato');
INSERT INTO CATEGORIAS (nome) VALUES ('Deserto');

INSERT INTO REGIOES (nome) VALUES ('Nordeste');
INSERT INTO REGIOES (nome) VALUES ('Sudeste');
INSERT INTO REGIOES (nome) VALUES ('Centro-Oeste');
INSERT INTO REGIOES (nome) VALUES ('Sul');
INSERT INTO REGIOES (nome) VALUES ('Norte');